### ISSUE TITLE
Release of this wrapper module?

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/tcpdf#1]
Hi @bugfolder. Would it be a good idea to make an official release of this module so that's included in backdropcms.org? I'm making use of this library in a few custom modules, and it'd be great to have the ability to make it a dependency and download this from the Installer.

**Comment by bugfolder** [comment]
Yup, don't know what I was waiting on. Released!

**Comment by argiepiano** [comment]
Thank you!
