### ISSUE TITLE
tcpdf.php found twice in module

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/tcpdf#7]
tcpdf.php is present twice in the module's `tcpdf` folder. And they are different versions (6.3.2 and 6.6.2). This can cause problems.

**Comment by bugfolder** [comment]
Huh? What's the two file paths within the folder? I'm not seeing it.

**Comment by argiepiano** [comment]
Sorry, let me clarify: there are two files named `tcpdf.php` in the module. 
- `tcpdf.php` (in the module root) AND
- `tcpdf/tcpdf.php`

**Comment by bugfolder** [comment]
I don't think there's one at module root. I just downloaded the current version of the module and here's what I see at module root:

```
tcpdf % ls -la
total 120
drwxr-xr-x@   9 <me>  staff    288 Feb 24 09:52 .
drwx------@ 380 <me>  staff  12160 Feb 24 09:52 ..
-rw-r--r--@   1 <me>  staff   6148 Feb 24 09:51 .DS_Store
-rw-r--r--@   1 <me>  staff  35149 May 19  2023 LICENSE
-rw-r--r--@   1 <me>  staff   1185 May 19  2023 README.md
drwxr-xr-x@  19 <me>  staff    608 Feb 24 09:52 tcpdf
-rw-r--r--@   1 <me>  staff    209 May 19  2023 tcpdf.info
-rw-r--r--@   1 <me>  staff    793 May 19  2023 tcpdf.install
-rw-r--r--@   1 <me>  staff    174 May 19  2023 tcpdf.module
tcpdf % 
```

**Comment by argiepiano** [comment]
Oops, I had a folder in my test site modules folder called tcpdf from before, so when I installed the module, it kept some old files in there. Sorry for the false alarm.

**Comment by bugfolder** [comment]
Was guessing it was something like that, but hey, when @argiepiano talks, it usually pays to listen! 😉

**Comment by argiepiano** [comment]
haha I talk a lot of BS sometime...
